import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

import 'task_telemetry_service.dart';

/// A single exact find/replace patch returned by the existing Nemotron worker.
class UpgradePatch {
  final String file;
  final String find;
  final String replace;

  const UpgradePatch({
    required this.file,
    required this.find,
    required this.replace,
  });

  factory UpgradePatch.fromJson(Map<String, dynamic> json) {
    final file = json['file'];
    final find = json['find'];
    final replace = json['replace'];
    if (file is! String || find is! String || replace is! String) {
      throw const FormatException(
        'Patch must contain file, find, and replace strings.',
      );
    }
    return UpgradePatch(file: file, find: find, replace: replace);
  }

  Map<String, dynamic> toJson() => {
    'file': file,
    'find': find,
    'replace': replace,
  };
}

class UpgradeProposal {
  final String problem;
  final String task;
  final String reason;
  final List<String> allowedFiles;
  final List<UpgradePatch> patches;
  final String? proposalFile;

  const UpgradeProposal({
    required this.problem,
    required this.task,
    required this.reason,
    required this.allowedFiles,
    required this.patches,
    this.proposalFile,
  });
}

typedef UpgradeWorkerInvoker =
    Future<Map<String, dynamic>> Function({
      required String repoPath,
      required List<String> allowedFiles,
      required String task,
      required Map<String, dynamic>? proposal,
      required bool apply,
    });

typedef UpgradeValidationInvoker =
    Future<UpgradeValidationResult> Function(String repoPath);

class UpgradeValidationResult {
  final bool passed;
  final String evidence;

  const UpgradeValidationResult({required this.passed, required this.evidence});
}

typedef CheckpointStorageProvider = Future<Directory> Function(String repoPath);

class _StoredCheckpoint {
  final UpgradeHistoryEntry entry;
  final String repoPath;
  final Map<String, String> contents;
  final Map<String, String> workingContents;

  const _StoredCheckpoint({
    required this.entry,
    required this.repoPath,
    required this.contents,
    this.workingContents = const {},
  });

  Map<String, dynamic> toJson() => {
    ...entry.toJson(),
    'repo_path': repoPath,
    'contents': contents,
    'working_contents': workingContents,
  };

  static _StoredCheckpoint fromJson(Map<String, dynamic> json) {
    final files = (json['files'] as List? ?? const [])
        .whereType<String>()
        .toList(growable: false);
    Map<String, String> decodeContents(Object? raw) => raw is Map
        ? <String, String>{
            for (final entry in raw.entries)
              entry.key.toString(): entry.value.toString(),
          }
        : <String, String>{};
    final contents = decodeContents(json['contents']);
    final workingContents = decodeContents(json['working_contents']);
    return _StoredCheckpoint(
      repoPath: json['repo_path']?.toString() ?? '',
      contents: contents,
      workingContents: workingContents,
      entry: UpgradeHistoryEntry(
        id: json['id']?.toString() ?? '',
        createdAt:
            DateTime.tryParse(json['created_at']?.toString() ?? '') ??
            DateTime.fromMillisecondsSinceEpoch(0, isUtc: true),
        status: ControlledUpgradeService._sanitize(
          json['status']?.toString() ?? 'unknown',
        ),
        files: files,
        changeSummary: ControlledUpgradeService._sanitize(
          json['change_summary']?.toString() ?? '',
        ),
        validationEvidence: ControlledUpgradeService._sanitize(
          json['validation_evidence']?.toString() ?? '',
        ),
        finalResult: ControlledUpgradeService._sanitize(
          json['final_result']?.toString() ?? '',
        ),
      ),
    );
  }
}

/// Controlled, development-only workflow for proposals generated by the
/// existing tools/nemotron_coding_worker.py worker.
///
/// This service never accepts arbitrary generated files. It permits only the
/// explicitly supplied existing files, requires one exact find/replace patch,
/// snapshots the original contents before applying, and restores that snapshot
/// when validation or testing fails.
class ControlledUpgradeService {
  static final ControlledUpgradeService shared = ControlledUpgradeService._();

  ControlledUpgradeService._({
    UpgradeWorkerInvoker? worker,
    UpgradeValidationInvoker? validator,
    CheckpointStorageProvider? checkpointStorage,
  }) : _worker = worker ?? _runExistingWorker,
       _validator = validator ?? _runValidation,
       _checkpointStorage =
           checkpointStorage ?? ((_) => getApplicationSupportDirectory());

  @visibleForTesting
  ControlledUpgradeService.forTesting({
    required UpgradeWorkerInvoker worker,
    required UpgradeValidationInvoker validator,
    CheckpointStorageProvider? checkpointStorage,
  }) : _worker = worker,
       _validator = validator,
       _checkpointStorage =
           checkpointStorage ?? ((repoPath) async => Directory(repoPath));

  final UpgradeWorkerInvoker _worker;
  final UpgradeValidationInvoker _validator;
  final CheckpointStorageProvider _checkpointStorage;
  UpgradeProposal? _proposal;
  Map<String, String> _originalContents = const {};
  String? _repoPath;
  String? _activeCheckpointId;
  Directory? _checkpointDirectory;
  final List<_StoredCheckpoint> _history = <_StoredCheckpoint>[];
  Map<String, String> _lastKnownWorkingContents = <String, String>{};
  bool _historyLoaded = false;
  UpgradeExecutionPlan? _upgradePlan;
  String? _lastProblem;
  String? _lastTask;
  List<String> _lastAllowedFiles = const [];
  int _proposalAttempts = 0;
  static const int _maxProposalAttempts = 2;

  TaskDeveloperSnapshot get state =>
      TaskTelemetryService.shared.developerState.value;

  List<UpgradeHistoryEntry> get history =>
      List<UpgradeHistoryEntry>.unmodifiable(
        _history.map((checkpoint) => checkpoint.entry),
      );

  UpgradeExecutionPlan? get upgradePlan => _upgradePlan;

  Future<void> loadHistory(String repoPath) async {
    if (!_isAbsoluteExistingDirectory(repoPath)) return;
    final normalizedRepo = _absolutePath(repoPath);
    _checkpointDirectory = await _storageDirectory(normalizedRepo);
    final manifest = File('${_checkpointDirectory!.path}/history.json');
    _history.clear();
    if (await manifest.exists()) {
      try {
        final decoded = jsonDecode(await manifest.readAsString());
        if (decoded is List) {
          _history.addAll(
            decoded
                .whereType<Map>()
                .map(
                  (item) => _StoredCheckpoint.fromJson(
                    Map<String, dynamic>.from(item),
                  ),
                )
                .where(
                  (checkpoint) =>
                      checkpoint.repoPath == normalizedRepo &&
                      checkpoint.contents.isNotEmpty,
                ),
          );
        }
      } on Object {
        _history.clear();
      }
    }
    _repoPath = normalizedRepo;
    _lastKnownWorkingContents = <String, String>{};
    for (final checkpoint in _history.reversed) {
      if (checkpoint.entry.status == 'validated' &&
          checkpoint.workingContents.isNotEmpty) {
        _lastKnownWorkingContents = Map<String, String>.from(
          checkpoint.workingContents,
        );
        break;
      }
    }
    _historyLoaded = true;
    _publishHistory();
  }

  Future<void> _createExecutionPlan({
    required String repoPath,
    required String request,
    required List<String> allowedFiles,
  }) async {
    final dependencies = <String, List<String>>{};
    for (final file in allowedFiles) {
      final source = await _readProjectFile(repoPath, file);
      final imports = <String>[];
      for (final match in RegExp(
        r'''(?:import|export)\s+['"]package:[^/]+/([^'"]+)['"]''',
      ).allMatches(source)) {
        final relative = match.group(1);
        if (relative != null && allowedFiles.contains(relative)) {
          imports.add(relative);
        }
      }
      dependencies[file] = imports.toSet().toList(growable: false);
    }
    final selectedTests = await _selectTests(repoPath, allowedFiles);
    final feature = request.toLowerCase();
    final uiStage =
        feature.contains('ui') ||
        feature.contains('screen') ||
        feature.contains('page') ||
        feature.contains('button') ||
        feature.contains('theme');
    final serviceStage =
        feature.contains('service') ||
        feature.contains('voice') ||
        feature.contains('automation') ||
        feature.contains('provider');
    final stages = <UpgradePlanStage>[
      UpgradePlanStage(
        id: 'inspect',
        title: 'Inspect current architecture',
        status: 'completed',
        requiresPatch: false,
        files: const [],
        dependencies: const [],
        selectedTests: const [],
        expectedResult:
            'Existing services and extension points are understood.',
      ),
      UpgradePlanStage(
        id: 'impact',
        title: 'Identify files and dependencies',
        status: 'completed',
        requiresPatch: false,
        files: allowedFiles,
        dependencies: dependencies.values
            .expand((items) => items)
            .toSet()
            .toList(),
        selectedTests: selectedTests,
        expectedResult: 'Only explicitly allowed project files are in scope.',
      ),
      UpgradePlanStage(
        id: 'design',
        title: 'Design minimal change set',
        status: 'completed',
        requiresPatch: false,
        files: const [],
        dependencies: const [],
        selectedTests: const [],
        expectedResult: 'The request is split into bounded, reviewable stages.',
      ),
      UpgradePlanStage(
        id: 'implement_ui',
        title: uiStage
            ? 'Implement the UI change'
            : 'Implement the primary change',
        status: 'ready',
        requiresPatch: true,
        files: allowedFiles,
        dependencies: dependencies.values
            .expand((items) => items)
            .toSet()
            .toList(),
        selectedTests: selectedTests,
        expectedResult:
            'The primary change is applied only to the selected files.',
      ),
      UpgradePlanStage(
        id: 'connect_services',
        title: serviceStage
            ? 'Connect existing state and services'
            : 'Connect existing state',
        status: 'pending',
        requiresPatch: true,
        files: allowedFiles,
        dependencies: dependencies.values
            .expand((items) => items)
            .toSet()
            .toList(),
        selectedTests: selectedTests,
        expectedResult:
            'Existing services are reused without creating duplicate architecture.',
      ),
      UpgradePlanStage(
        id: 'tests',
        title: 'Add or update focused tests',
        status: selectedTests.isEmpty ? 'skipped' : 'pending',
        requiresPatch: selectedTests.isNotEmpty,
        files: selectedTests,
        dependencies: const [],
        selectedTests: selectedTests,
        expectedResult:
            'Focused tests cover the requested behavior and failure paths.',
      ),
      UpgradePlanStage(
        id: 'validate',
        title: 'Validate and inspect errors',
        status: 'pending',
        requiresPatch: false,
        files: const [],
        dependencies: const [],
        selectedTests: const [],
        expectedResult:
            'Static analysis and selected tests pass before the stage is kept.',
      ),
      UpgradePlanStage(
        id: 'report',
        title: 'Report completion',
        status: 'pending',
        requiresPatch: false,
        files: const [],
        dependencies: const [],
        selectedTests: const [],
        expectedResult:
            'Files, validation, tests, and any errors are reported clearly.',
      ),
    ];
    _upgradePlan = UpgradeExecutionPlan(
      id: DateTime.now().toUtc().microsecondsSinceEpoch.toString(),
      createdAt: DateTime.now().toUtc(),
      request: _sanitize(request),
      status: 'planned',
      currentStageIndex: 3,
      impactedFiles: allowedFiles,
      dependencies: dependencies,
      selectedTests: selectedTests,
      stages: stages,
    );
    _publishPlan();
  }

  Future<List<String>> _selectTests(
    String repoPath,
    List<String> allowedFiles,
  ) async {
    final testRoot = Directory('$repoPath/test');
    if (!await testRoot.exists()) return const [];
    final terms = allowedFiles
        .map(
          (file) => file.split('/').last.replaceAll('.dart', '').toLowerCase(),
        )
        .where((term) => term.isNotEmpty)
        .toSet();
    final selected = <String>[];
    await for (final entity in testRoot.list(
      recursive: true,
      followLinks: false,
    )) {
      if (entity is! File || !entity.path.endsWith('_test.dart')) continue;
      final relative = entity.path
          .substring(repoPath.length + 1)
          .replaceAll('\\', '/');
      final content = await entity.readAsString();
      final lower = content.toLowerCase();
      if (terms.any(lower.contains)) selected.add(relative);
    }
    return selected..sort();
  }

  void _publishPlan() {
    TaskTelemetryService.shared.recordUpgradePlan(_upgradePlan);
  }

  void _updatePlan({
    String? status,
    int? currentStageIndex,
    List<UpgradePlanStage>? stages,
    String? lastError,
  }) {
    final plan = _upgradePlan;
    if (plan == null) return;
    _upgradePlan = plan.copyWith(
      status: status,
      currentStageIndex: currentStageIndex,
      stages: stages,
      lastError: lastError,
    );
    _publishPlan();
  }

  void _updateCurrentStage({
    required String status,
    int? attempts,
    String? error,
  }) {
    final plan = _upgradePlan;
    if (plan == null || plan.currentStageIndex >= plan.stages.length) return;
    final stages = List<UpgradePlanStage>.from(plan.stages);
    stages[plan.currentStageIndex] = stages[plan.currentStageIndex].copyWith(
      status: status,
      attempts: attempts,
      error: error,
    );
    _updatePlan(stages: stages);
  }

  Future<void> _rereadAllowedFiles() async {
    final repoPath = _repoPath;
    if (repoPath == null) return;
    for (final file in _lastAllowedFiles) {
      await _readProjectFile(repoPath, file);
    }
  }

  Future<void> _requestProposalForCurrentStage({
    required String problem,
    required String task,
    required List<String> files,
  }) async {
    final repoPath = _repoPath;
    final plan = _upgradePlan;
    if (repoPath == null ||
        plan == null ||
        plan.currentStageIndex >= plan.stages.length) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'No executable implementation stage is available.',
        result: 'No change was proposed or applied.',
      );
      return;
    }
    final stage = plan.stages[plan.currentStageIndex];
    final stageFiles = stage.files.isEmpty ? files : stage.files;
    final stageTask =
        '''$task

Controlled implementation stage: ${stage.title}
Expected result: ${stage.expectedResult}
Selected tests: ${stage.selectedTests.join(', ')}
Return only one exact patch for an explicitly allowed existing file.''';
    String lastError = '';
    for (var attempt = 1; attempt <= _maxProposalAttempts; attempt++) {
      _proposalAttempts = attempt;
      _updateCurrentStage(status: 'proposing', attempts: attempt, error: '');
      try {
        await _rereadAllowedFiles();
        final response = await _worker(
          repoPath: repoPath,
          allowedFiles: stageFiles,
          task: stageTask,
          proposal: null,
          apply: false,
        );
        final proposal = _parseProposal(
          response,
          problem: problem,
          task: stageTask,
          allowedFiles: stageFiles,
        );
        _validateProposalOnDisk(proposal, repoPath);
        _proposal = proposal;
        _updateCurrentStage(status: 'awaiting_approval', attempts: attempt);
        _updatePlan(status: 'awaiting_approval');
        _publish(
          stage: 'upgrade_proposed',
          problem: problem,
          files: stageFiles,
          reason: proposal.reason,
          evidence:
              'Stage ${stage.title} produced one validated exact patch. Nothing has been applied.',
          finalResult: 'Review the staged change before applying it.',
          canApply: true,
        );
        return;
      } catch (error) {
        lastError = _sanitize('$error');
        _updateCurrentStage(
          status: attempt < _maxProposalAttempts ? 'recovering' : 'failed',
          attempts: attempt,
          error: lastError,
        );
        _updatePlan(
          status: attempt < _maxProposalAttempts ? 'recovering' : 'failed',
          lastError: lastError,
        );
        if (attempt < _maxProposalAttempts) {
          await _rereadAllowedFiles();
        }
      }
    }
    _publishFailure(
      stage: 'upgrade_failed',
      observed: 'The staged proposal remained invalid after bounded recovery.',
      evidence: lastError,
      result:
          'No change was applied. The affected files were re-read and the workflow stopped safely.',
    );
  }

  Future<void> prepareNextStage() async {
    final plan = _upgradePlan;
    final repoPath = _repoPath;
    final task = _lastTask;
    final problem = _lastProblem;
    if (plan == null || repoPath == null || task == null || problem == null) {
      return;
    }
    if (plan.currentStageIndex < plan.stages.length &&
        plan.stages[plan.currentStageIndex].requiresPatch &&
        plan.stages[plan.currentStageIndex].status != 'validated') {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'The current implementation stage has not passed validation.',
        result:
            'The next stage was not prepared; review or roll back the current stage first.',
      );
      return;
    }
    final nextIndex = plan.stages.indexWhere(
      (stage) => stage.requiresPatch && stage.status == 'pending',
    );
    if (nextIndex < 0) {
      _updatePlan(
        status: 'complete',
        currentStageIndex: plan.stages.length - 1,
      );
      return;
    }
    _proposal = null;
    _updatePlan(status: 'planning', currentStageIndex: nextIndex);
    await _requestProposalForCurrentStage(
      problem: problem,
      task: task,
      files: _lastAllowedFiles,
    );
  }

  Future<void> identifyAndPropose({
    required String repoPath,
    required String problem,
    required String task,
    required List<String> allowedFiles,
  }) async {
    final safeProblem = _sanitize(problem);
    final safeTask = _sanitize(task);
    final files = _validateAllowedFiles(allowedFiles);
    if (safeProblem.isEmpty || safeTask.isEmpty || files.isEmpty) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'The upgrade request was incomplete or had no allowed files.',
        result: 'No change was proposed or applied.',
      );
      return;
    }
    if (!_isAbsoluteExistingDirectory(repoPath)) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'The configured development project root was unavailable.',
        result: 'No project files were changed.',
      );
      return;
    }

    _repoPath = _absolutePath(repoPath);
    _lastProblem = safeProblem;
    _lastTask = safeTask;
    _lastAllowedFiles = files;
    _proposal = null;
    _originalContents = const {};
    _publish(
      stage: 'upgrade_identifying',
      problem: safeProblem,
      files: files,
      reason:
          'Building a dependency-aware staged plan before requesting a patch.',
      evidence: 'Allowed files: ${files.join(', ')}',
      finalResult: '',
      canApply: false,
    );

    try {
      await _ensureHistoryLoaded(_repoPath!);
      await _createExecutionPlan(
        repoPath: _repoPath!,
        request: safeTask,
        allowedFiles: files,
      );
      await _requestProposalForCurrentStage(
        problem: safeProblem,
        task: safeTask,
        files: files,
      );
    } catch (error) {
      _updatePlan(status: 'failed', lastError: _sanitize('$error'));
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'The staged development plan could not be created safely.',
        evidence: _sanitize('$error'),
        result: 'No change was applied.',
      );
    }
  }

  Future<void> applyValidateAndKeepOrRollback() async {
    final proposal = _proposal;
    final repoPath = _repoPath;
    if (proposal == null || repoPath == null) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'Apply was requested without a validated proposal.',
        result: 'No change was applied.',
      );
      return;
    }

    try {
      _updateCurrentStage(status: 'applying', attempts: _proposalAttempts);
      _updatePlan(status: 'applying');
      _validateProposalOnDisk(proposal, repoPath);
      _originalContents = {
        for (final patch in proposal.patches)
          patch.file: await _readProjectFile(repoPath, patch.file),
      };
      await _ensureHistoryLoaded(repoPath);
      final checkpoint = await _createCheckpoint(
        repoPath: repoPath,
        proposal: proposal,
        contents: _originalContents,
      );
      _activeCheckpointId = checkpoint.entry.id;
      _publish(
        stage: 'upgrade_applying',
        problem: proposal.problem,
        files: proposal.allowedFiles,
        reason: proposal.reason,
        evidence: 'Original contents were snapshotted before applying.',
        finalResult: '',
        canApply: false,
      );

      final response = await _worker(
        repoPath: repoPath,
        allowedFiles: proposal.allowedFiles,
        task: proposal.task,
        proposal: {
          'format': 'agent_cypher_patch_v1',
          'edits': proposal.patches.map((patch) => patch.toJson()).toList(),
          if (proposal.proposalFile != null)
            'proposal_file': proposal.proposalFile,
        },
        apply: true,
      );
      if (response['ok'] == false || response['applied'] == false) {
        throw StateError(
          _sanitize(
            '${response['error'] ?? 'Worker did not apply the validated proposal.'}',
          ),
        );
      }

      _publish(
        stage: 'upgrade_validating',
        problem: proposal.problem,
        files: proposal.allowedFiles,
        reason: proposal.reason,
        evidence: 'The worker reported the exact approved patch as applied.',
        finalResult: '',
      );
      final validation = await _validator(repoPath);
      if (!validation.passed) {
        _updateCurrentStage(
          status: 'validation_failed',
          error: _sanitize(validation.evidence),
        );
        _updatePlan(
          status: 'rolling_back',
          lastError: _sanitize(validation.evidence),
        );
        await _rollbackInternal(repoPath, proposal, validation.evidence);
        return;
      }

      final workingContents = {
        for (final patch in proposal.patches)
          patch.file: await _readProjectFile(repoPath, patch.file),
      };
      await _markCheckpoint(
        checkpointId: checkpoint.entry.id,
        status: 'validated',
        validationEvidence: validation.evidence,
        finalResult: 'Change kept because validation and tests passed.',
        workingContents: workingContents,
      );
      _lastKnownWorkingContents = workingContents;
      _updateCurrentStage(status: 'validated', attempts: _proposalAttempts);
      _updatePlan(status: 'stage_validated');
      _publish(
        stage: 'upgrade_kept',
        problem: proposal.problem,
        files: proposal.allowedFiles,
        reason: proposal.reason,
        evidence: validation.evidence,
        finalResult: 'Change kept because validation and tests passed.',
        canApply: false,
      );
    } catch (error) {
      await _rollbackInternal(repoPath, proposal, _sanitize('$error'));
    }
  }

  Future<void> rollbackLastChange() async {
    await _ensureHistoryForCurrentProject();
    if (_history.isNotEmpty) {
      await rollbackTo(_history.last.entry.id);
      return;
    }
    final proposal = _proposal;
    final repoPath = _repoPath;
    if (proposal == null || repoPath == null || _originalContents.isEmpty) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed:
            'Rollback was requested without an available change snapshot.',
        result: 'No files were changed by rollback.',
      );
      return;
    }
    await _rollbackInternal(repoPath, proposal, 'Manual rollback requested.');
  }

  Future<void> undoChanges(int count) async {
    await _ensureHistoryForCurrentProject();
    if (count <= 0 || _history.isEmpty) return;
    final index = (_history.length - count).clamp(0, _history.length - 1);
    await rollbackTo(_history[index].entry.id);
  }

  Future<void> rollbackTo(String checkpointId) async {
    await _ensureHistoryForCurrentProject();
    final index = _history.indexWhere(
      (checkpoint) => checkpoint.entry.id == checkpointId,
    );
    if (index < 0) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'The selected source checkpoint was not found.',
        result: 'No files were changed by rollback.',
      );
      return;
    }
    final checkpoint = _history[index];
    try {
      await _restoreContents(checkpoint.repoPath, checkpoint.contents);
      for (var i = index; i < _history.length; i++) {
        final entry = _history[i].entry;
        _history[i] = _StoredCheckpoint(
          entry: UpgradeHistoryEntry(
            id: entry.id,
            createdAt: entry.createdAt,
            status: 'undone',
            files: entry.files,
            changeSummary: entry.changeSummary,
            validationEvidence: entry.validationEvidence,
            finalResult: 'Restored by source rollback.',
          ),
          repoPath: checkpoint.repoPath,
          contents: _history[i].contents,
          workingContents: _history[i].workingContents,
        );
      }
      await _persistHistory();
      _publishHistory();
      TaskTelemetryService.shared.recordUpgradeState(
        stage: 'upgrade_rolled_back',
        files: checkpoint.entry.files,
        evidence: 'Restored checkpoint ${checkpoint.entry.id}.',
        finalResult:
            'Selected source state restored; previous checkpoints retained.',
        canApply: false,
      );
    } on Object catch (error) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'Source rollback could not be completed safely.',
        evidence: _sanitize('$error'),
        result: 'No further automatic source changes will be attempted.',
      );
    }
  }

  Future<void> restoreLastKnownWorking() async {
    await _ensureHistoryForCurrentProject();
    if (_history.isEmpty) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'No validated working checkpoint is available.',
        result: 'No files were changed by restore.',
      );
      return;
    }
    final working = _history.lastWhere(
      (checkpoint) =>
          checkpoint.entry.status == 'validated' &&
          checkpoint.workingContents.isNotEmpty,
      orElse: () => _StoredCheckpoint(
        entry: UpgradeHistoryEntry(
          id: '',
          createdAt: DateTime.fromMillisecondsSinceEpoch(0),
          status: 'none',
          files: const [],
          changeSummary: '',
          validationEvidence: '',
          finalResult: '',
        ),
        repoPath: '',
        contents: const {},
      ),
    );
    if (working.entry.id.isEmpty) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'No validated working checkpoint is available.',
        result: 'No files were changed by restore.',
      );
      return;
    }
    try {
      final contents = _lastKnownWorkingContents.isNotEmpty
          ? _lastKnownWorkingContents
          : working.workingContents;
      await _restoreContents(working.repoPath, contents);
      TaskTelemetryService.shared.recordUpgradeState(
        stage: 'upgrade_restored_working',
        files: working.entry.files,
        evidence: 'Restored the last validated source state.',
        finalResult: 'Last known working state restored.',
        canApply: false,
      );
    } on Object catch (error) {
      _publishFailure(
        stage: 'upgrade_failed',
        observed: 'Last-known-working restoration failed safely.',
        evidence: _sanitize('$error'),
        result: 'No further automatic source changes will be attempted.',
      );
    }
  }

  Future<void> _rollbackInternal(
    String repoPath,
    UpgradeProposal proposal,
    String evidence,
  ) async {
    try {
      await _restoreContents(repoPath, _originalContents);
      if (_activeCheckpointId != null) {
        await _markCheckpoint(
          checkpointId: _activeCheckpointId!,
          status: 'rolled_back',
          validationEvidence: evidence,
          finalResult: 'Change was rolled back; it was not kept.',
        );
      }
      _publish(
        stage: 'upgrade_rolled_back',
        problem: proposal.problem,
        files: proposal.allowedFiles,
        reason: proposal.reason,
        evidence: _sanitize(evidence),
        finalResult: 'Change was rolled back; it was not kept.',
        canApply: false,
      );
      _activeCheckpointId = null;
      _updateCurrentStage(status: 'rolled_back', error: _sanitize(evidence));
      _updatePlan(status: 'rolled_back', lastError: _sanitize(evidence));
    } catch (error) {
      _updateCurrentStage(
        status: 'rollback_failed',
        error: _sanitize('$error'),
      );
      _updatePlan(status: 'blocked', lastError: _sanitize('$error'));
      _publishFailure(
        stage: 'upgrade_failed',
        observed:
            'Validation failed and rollback could not be completed safely.',
        evidence: _sanitize('$error'),
        result:
            'Manual inspection is required; no further automatic changes will be attempted.',
      );
    }
  }

  Future<Directory> _storageDirectory(String repoPath) async {
    final root = await _checkpointStorage(repoPath);
    final key = base64Url.encode(utf8.encode(repoPath)).replaceAll('=', '');
    final directory = Directory('${root.path}/agent_cypher_checkpoints/$key');
    await directory.create(recursive: true);
    return directory;
  }

  Future<void> _ensureHistoryLoadedFor(String repoPath) async {
    final normalized = _absolutePath(repoPath);
    if (_historyLoaded && _repoPath == normalized) return;
    await loadHistory(normalized);
  }

  Future<void> _ensureHistoryLoaded(String repoPath) async {
    await _ensureHistoryLoadedFor(repoPath);
  }

  Future<void> _ensureHistoryForCurrentProject() async {
    final repoPath = _repoPath;
    if (repoPath != null) {
      await _ensureHistoryLoadedFor(repoPath);
    }
  }

  Future<_StoredCheckpoint> _createCheckpoint({
    required String repoPath,
    required UpgradeProposal proposal,
    required Map<String, String> contents,
  }) async {
    final id = '${DateTime.now().toUtc().microsecondsSinceEpoch}';
    final entry = UpgradeHistoryEntry(
      id: id,
      createdAt: DateTime.now().toUtc(),
      status: 'pending',
      files: proposal.patches
          .map((patch) => patch.file)
          .toList(growable: false),
      changeSummary: _changeSummary(proposal),
      validationEvidence: 'Validation pending.',
      finalResult: 'Undo available immediately from this checkpoint.',
    );
    final checkpoint = _StoredCheckpoint(
      entry: entry,
      repoPath: _absolutePath(repoPath),
      contents: Map<String, String>.from(contents),
    );
    _history.add(checkpoint);
    await _persistHistory();
    _publishHistory();
    return checkpoint;
  }

  Future<void> _markCheckpoint({
    required String checkpointId,
    required String status,
    required String validationEvidence,
    required String finalResult,
    Map<String, String> workingContents = const {},
  }) async {
    final index = _history.indexWhere(
      (checkpoint) => checkpoint.entry.id == checkpointId,
    );
    if (index < 0) return;
    final current = _history[index];
    _history[index] = _StoredCheckpoint(
      entry: UpgradeHistoryEntry(
        id: current.entry.id,
        createdAt: current.entry.createdAt,
        status: status,
        files: current.entry.files,
        changeSummary: current.entry.changeSummary,
        validationEvidence: _sanitize(validationEvidence),
        finalResult: _sanitize(finalResult),
      ),
      repoPath: current.repoPath,
      contents: current.contents,
      workingContents: workingContents.isEmpty
          ? current.workingContents
          : Map<String, String>.from(workingContents),
    );
    await _persistHistory();
    _publishHistory();
  }

  Future<void> _restoreContents(
    String repoPath,
    Map<String, String> contents,
  ) async {
    for (final entry in contents.entries) {
      await _projectFile(
        repoPath,
        entry.key,
      ).writeAsString(entry.value, flush: true);
    }
  }

  Future<void> _persistHistory() async {
    final directory =
        _checkpointDirectory ?? await _storageDirectory(_repoPath ?? '');
    _checkpointDirectory = directory;
    final manifest = File('${directory.path}/history.json');
    final temp = File('${directory.path}/history.json.tmp');
    await temp.writeAsString(
      const JsonEncoder.withIndent('  ').convert(<Map<String, dynamic>>[
        for (final checkpoint in _history) checkpoint.toJson(),
      ]),
      flush: true,
    );
    await temp.rename(manifest.path);
  }

  void _publishHistory() {
    TaskTelemetryService.shared.recordUpgradeHistory(history);
  }

  static String _changeSummary(UpgradeProposal proposal) {
    final patch = proposal.patches.single;
    return _sanitize(
      '${patch.file}: replace “${patch.find}” with “${patch.replace}”.',
    );
  }

  UpgradeProposal _parseProposal(
    Map<String, dynamic> response, {
    required String problem,
    required String task,
    required List<String> allowedFiles,
  }) {
    if (response['ok'] == false) {
      throw StateError(_sanitize('${response['error'] ?? 'Worker failed.'}'));
    }
    final rawProposal = response['proposal'] is Map
        ? Map<String, dynamic>.from(response['proposal'] as Map)
        : response;
    final rawEdits = rawProposal['edits'];
    if (rawEdits is! List || rawEdits.length != 1) {
      throw const FormatException(
        'A controlled upgrade requires exactly one patch.',
      );
    }
    final patches = rawEdits
        .map(
          (item) =>
              UpgradePatch.fromJson(Map<String, dynamic>.from(item as Map)),
        )
        .toList(growable: false);
    return UpgradeProposal(
      problem: problem,
      task: task,
      reason: _sanitize(
        '${rawProposal['reason'] ?? response['summary'] ?? 'Structured proposal from the existing Nemotron worker.'}',
      ),
      allowedFiles: allowedFiles,
      patches: patches,
      proposalFile: rawProposal['proposal_file'] as String?,
    );
  }

  void _validateProposalOnDisk(UpgradeProposal proposal, String repoPath) {
    if (proposal.patches.length != 1) {
      throw const FormatException(
        'Only one patch is allowed per upgrade attempt.',
      );
    }
    final patch = proposal.patches.single;
    if (!proposal.allowedFiles.contains(patch.file) ||
        !_isSafeRelativePath(patch.file)) {
      throw const FormatException(
        'The proposed file is outside the explicit allow-list.',
      );
    }
    if (patch.find.isEmpty ||
        patch.replace.isEmpty ||
        patch.find == patch.replace) {
      throw const FormatException(
        'The patch must be a non-empty, changing exact replacement.',
      );
    }
    final original = _projectFile(repoPath, patch.file).readAsStringSync();
    if (original.split(patch.find).length - 1 != 1) {
      throw const FormatException(
        'The exact find text must occur once in the current file.',
      );
    }
  }

  static List<String> _validateAllowedFiles(List<String> files) {
    final normalized = <String>{};
    for (final file in files) {
      final value = file.trim().replaceAll('\\', '/');
      if (_isSafeRelativePath(value)) normalized.add(value);
    }
    return normalized.toList(growable: false);
  }

  static bool _isSafeRelativePath(String value) {
    if (value.isEmpty || value.startsWith('/') || value.contains(':')) {
      return false;
    }
    final parts = value.split('/');
    return !parts.contains('..') &&
        !parts.contains('.') &&
        !value.endsWith('/');
  }

  static bool _isAbsoluteExistingDirectory(String path) =>
      _absolutePath(path).startsWith('/') && Directory(path).existsSync();

  static String _absolutePath(String path) => Directory(path).absolute.path;

  static File _projectFile(String repoPath, String relative) {
    final root = Directory(repoPath).resolveSymbolicLinksSync();
    final file = File('$root/${relative.replaceAll('\\', '/')}').absolute;
    if (!file.path.startsWith('$root/')) {
      throw const FormatException('Project path escaped the configured root.');
    }
    if (file.existsSync() &&
        !file.resolveSymbolicLinksSync().startsWith('$root/')) {
      throw const FormatException(
        'Project symlink escaped the configured root.',
      );
    }
    return file;
  }

  static Future<String> _readProjectFile(String repoPath, String relative) =>
      _projectFile(repoPath, relative).readAsString();

  void _publish({
    required String stage,
    String? problem,
    List<String>? files,
    String? reason,
    String? evidence,
    String? finalResult,
    bool? canApply,
  }) {
    TaskTelemetryService.shared.recordUpgradeState(
      stage: stage,
      problem: problem,
      files: files,
      reason: reason,
      evidence: evidence,
      finalResult: finalResult,
      canApply: canApply,
    );
  }

  void _publishFailure({
    required String stage,
    required String observed,
    String evidence = '',
    required String result,
  }) {
    _publish(
      stage: stage,
      evidence: evidence.isEmpty ? observed : '$observed $evidence',
      finalResult: result,
      canApply: false,
    );
  }

  static String _sanitize(String value) {
    var safe = value.trim();
    safe = safe.replaceAll(
      RegExp(
        r'\b(?:sk-|nvapi-|github_pat_)[A-Za-z0-9_-]+',
        caseSensitive: false,
      ),
      '[REDACTED_SECRET]',
    );
    safe = safe.replaceAll(
      RegExp(
        r'\b(?:api[_ -]?key|access[_ -]?token|token|password|secret|credential)\s*[:=]\s*[^\s,;]+',
        caseSensitive: false,
      ),
      '[REDACTED_SECRET]',
    );
    return safe.length > 500 ? '${safe.substring(0, 500)}…' : safe;
  }

  static Future<Map<String, dynamic>> _runExistingWorker({
    required String repoPath,
    required List<String> allowedFiles,
    required String task,
    required Map<String, dynamic>? proposal,
    required bool apply,
  }) async {
    try {
      final tempDir = await Directory.systemTemp.createTemp(
        'agent_cypher_upgrade_',
      );
      final proposalFile = File('${tempDir.path}/proposal.json');
      final args = <String>[
        'tools/nemotron_coding_worker.py',
        '--repo',
        repoPath,
        '--task',
        task,
      ];
      for (final file in allowedFiles) {
        args.addAll(['--file', file]);
      }
      if (apply) {
        final proposalPath = proposal?['proposal_file'] as String?;
        if (proposalPath == null || proposalPath.isEmpty) {
          throw StateError(
            'The worker proposal file was unavailable for apply.',
          );
        }
        args.addAll(['--apply-proposal', proposalPath]);
      } else {
        args.addAll(['--proposal-file', proposalFile.path]);
      }
      final stopwatch = Stopwatch()..start();
      final result = await Process.run(
        'python3',
        args,
        workingDirectory: repoPath,
      );
      stopwatch.stop();
      final output = result.stdout is String ? result.stdout as String : '';
      TaskTelemetryService.shared.recordWorkspaceCommand(
        command: ['python3', ...args].join(' '),
        workingDirectory: repoPath,
        exitCode: result.exitCode,
        elapsedMs: stopwatch.elapsedMilliseconds,
        output: result.exitCode == 0 ? output : result.stderr.toString(),
      );
      if (result.exitCode != 0) {
        throw StateError(_sanitize(result.stderr.toString()));
      }
      final decoded = jsonDecode(output.trim());
      if (decoded is! Map) {
        throw const FormatException('Worker output was not JSON.');
      }
      final map = Map<String, dynamic>.from(decoded);
      if (!apply && await proposalFile.exists()) {
        map['proposal'] = jsonDecode(await proposalFile.readAsString());
        map['proposal']['proposal_file'] = proposalFile.path;
      }
      return map;
    } on Object catch (error) {
      return {'ok': false, 'error': _sanitize('$error')};
    }
  }

  static Future<UpgradeValidationResult> _runValidation(String repoPath) async {
    try {
      final flutter = const String.fromEnvironment(
        'FLUTTER_BIN',
        defaultValue: 'flutter',
      );
      final commands = <List<String>>[
        [flutter, 'analyze', '--no-fatal-infos'],
        [flutter, 'test'],
      ];
      final evidence = <String>[];
      for (final command in commands) {
        final stopwatch = Stopwatch()..start();
        final result = await Process.run(
          command.first,
          command.skip(1).toList(),
          workingDirectory: repoPath,
        ).timeout(const Duration(minutes: 5));
        stopwatch.stop();
        TaskTelemetryService.shared.recordWorkspaceCommand(
          command: command.join(' '),
          workingDirectory: repoPath,
          exitCode: result.exitCode,
          elapsedMs: stopwatch.elapsedMilliseconds,
          output: result.exitCode == 0
              ? result.stdout.toString()
              : result.stderr.toString(),
        );
        evidence.add('${command.skip(1).join(' ')}: exit ${result.exitCode}');
        if (result.exitCode != 0) {
          return UpgradeValidationResult(
            passed: false,
            evidence: evidence.join('; '),
          );
        }
      }
      return UpgradeValidationResult(
        passed: true,
        evidence: evidence.join('; '),
      );
    } on Object catch (error) {
      return UpgradeValidationResult(
        passed: false,
        evidence: 'Validation unavailable or timed out: ${_sanitize('$error')}',
      );
    }
  }
}
